### ISSUE TITLE
‎

### ISSUE THREAD

**Issue by AlmightyLks** [DeveloperDrago/wait-a-damn-minute#1]

**Comment by thetayloredman** [comment]
wait a damn minute

**Comment by AlmightyLks** [comment]
‎

**Comment by DeveloperDrago** [comment]
# **Wait a Damn Minute 🤔**

**Comment by thetayloredman** [comment]
# waaaaaaaait a daaaaaaamn miiiinute

**Comment by thetayloredman** [comment]
# wwwwwaaaaaaaaiiiiiiiiiiiitttttttt aaaa ddddaaaaaaammmmnnn mmiiiinnnuuuuttteeee

**Comment by DeveloperDrago** [comment]
# **AAAAAAAAAAAA** **SILENTLY COMMENTS**

**Comment by thetayloredman** [comment]
# lmao

On-Behalf-Of: DeveloperDrago

**Comment by thetayloredman** [comment]
aw yeah you aren't an org
